#!/usr/bin/env python
import json
import tokenize
import re

# PARAMETERS INIT #

nParticipants = 145
nArticles = 183
gdf_name = "bipartite_nodes_CSCW2013_URL_time.gdf"  # input file name
json_name = "data"                                  # output file name (no .json nor .*)
sample_mode = False  # To generate the whole data, change sample_mode to false
rDel = None
if (sample_mode) :
    pDel = 10
    aDel = nParticipants + 10
    rDel = nParticipants + nArticles + 11
    json_name += "Sample.json"
else :
    pDel = nParticipants
    aDel = nParticipants + nArticles
    json_name += ".json"

# GDF TO JSON FUNCTION #

def regularjson (gdf_file) :

    content = gdf_file.readlines()
    json_data = {}
    elem_list = {}
    part = {}
    art = {}
    rel = {}
    part_list = []
    art_list = []
    rel_list = []
    saved = False

    json_file = open(json_name, "w")
    try:
        rDel
    except NameError:
        rDel = len(content)

    for i,c in enumerate(content) :
        if (i <= pDel and i > 0):
            elem_list = c.rstrip("'\n").split("','");

            if(len(elem_list) == 6):
                part = {}
                part['userId'] = elem_list[0]
                part['userLabel'] = elem_list[1]
                part['userLabelShort'] = elem_list[2]
                part['userType'] = elem_list[3]
                part['userUrl'] = elem_list[4]
                part['userDate'] = elem_list[5]
                part_list.append(part)

        elif (i > nParticipants and i <= aDel) :
            elem_list = c.rstrip("'\n").split("','");

            if(len(elem_list) == 6):
                art = {}
                art['paperId'] = elem_list[0]
                art['paperLabel'] = elem_list[1]
                art['paperLabelShort'] = elem_list[2]
                art['paperType'] = elem_list[3]
                art['paperUrl'] = elem_list[4]
                art['paperDate'] = elem_list[5]

                art_list.append(art)

        elif (i > nParticipants+nArticles+1 and i <= rDel) :
            elem_list = c.rstrip("'\n").split("','");

            if(len(elem_list) == 3):
                rel = {}
                rel['relUser'] = elem_list[0]
                rel['relPaper'] = elem_list[1]
                rel['relTime'] = elem_list[2]

                rel_list.append(rel)

    json_file.write("{\n\"users\" : " + json.dumps(part_list, json_file, indent=4))
    json_file.write(",\n\"papers\" : " + json.dumps(art_list, json_file, indent=4))
    json_file.write(",\n\"rel\" : " + json.dumps(rel_list, json_file, indent=4) + "\n}")

    return True

def hierarchyjson (gdf_file) :

    content = gdf_file.readlines()
    json_data = {}
    elem_list = {}
    part = {}
    data = {}
    art = {}
    rel = {}
    part_list = []
    art_list = []
    rel_list = []
    saved = False

    json_file = open(json_name, "w")
    try:
        rDel
    except NameError:
        rDel = len(content)

    for i,c in enumerate(content) :
        if (i <= pDel and i > 0):
            elem_list = c.rstrip("'\n").rstrip("'").split("','");

            if(len(elem_list) == 6):
                part = {}
                data = {}
                data['label'] = elem_list[1]
                data['labelShort'] = elem_list[2]
                data['url'] = elem_list[4]
                data['date'] = elem_list[5]
                part['name'] = "user."+elem_list[0][1:] + "." + elem_list[3]
                part['data'] = data
                part['imports'] = []
                part_list.append(part)

        elif (i > nParticipants and i <= aDel) :
            elem_list = c.rstrip("'\n").rstrip("'").split("','");

            if(len(elem_list) == 6):
                art = {}
                data = {}
                data['label'] = elem_list[1]
                data['labelShort'] = elem_list[2]
                data['url'] = elem_list[4]
                data['date'] = elem_list[5]
                art['name'] = "paper."+elem_list[0][1:] + "." + elem_list[3]
                art['data'] = data
                art['imports'] = []
                art_list.append(art)

        elif (i > nParticipants+nArticles+1 and i <= rDel) :
            elem_list = c.rstrip("'\n").rstrip("'").split("','");

            if(len(elem_list) == 3):
                rel = {}
                rel['relUser'] = elem_list[0][1:]
                rel['relPaper'] = elem_list[1]
                rel['relTime'] = elem_list[2]
                # part_list where name = "user."+elem_list[0] + ".user"
                currentUser = "user."+elem_list[0][1:]+".user"
                currentPaper = "paper."+elem_list[1]+".talk"
                for e in part_list:
                    if (e['name'] == currentUser):
                        e['imports'].append(currentPaper)

                rel_list.append(rel)


    json_file.write( json.dumps(part_list+art_list, json_file, indent=4) )
    #json_file.write(",\n\"rel\" : " + json.dumps(rel_list, json_file, indent=4) + "\n]")

    return True

def main () :

    # FILE POINTERS #
    gdf_file = open(gdf_name, "r")

    # JSON CREATION #
    if(sample_mode):
        print ("Note: Sample mode is on")

    #if( regularjson(gdf_file) ):
    #    print ("Written to: " + json_name + "\n")

    if( hierarchyjson(gdf_file) ):
        print ("Written to: " + json_name + "\n")

main();
